export const workbox = [
  // {
  //   id: 0,
  //   expired: true,
  //   name: 'Portfolio (Vue.js) *서버폐쇄',
  //   desc: 'Vue.js로 제작된 포트폴리오 페이지 입니다.',
  //   src: './assets/portfolio.gif',
  //   skills: '#Vue.js, #scss, #html, #MongoDB, #Express',
  //   href: ['https://port-0-portfolio2-6w1j2alm48bfok.sel5.cloudtype.app/'],
  //   githref: 'https://github.com/Sovidi/portfolio2',
  // },
  {
    id: 1,
    expired: false,
    name: 'Portfolio (Next.js)',
    desc: '현재 보고계신 Next.js 이식버전의 포트폴리오입니다.',
    src: './assets/portfolio.gif',
    skills: '#Next.js, #scss, #html, #MongoDB, #Express',
    href: ['https://portfolio3-blue.vercel.app/'],
    githref: 'https://github.com/Sovidi/portfolio3',
  },
  {
    id: 2,
    expired: false,
    name: 'Wonder place',
    desc: '원더플레이스 브랜드관 소개페이지 클론코딩',
    src: './assets/wonderplace.png',
    skills: '#javascript, #scss, #html, #jQuery',
    href: ['https://sovidi.github.io/wonderplace_clone/'],
    githref: 'https://github.com/Sovidi/wonderplace_clone',
  },
  {
    id: 3,
    expired: false,
    name: 'Everland',
    desc: '에버랜드 홈페이지 리뉴얼',
    src: './assets/everland.png',
    skills: '#javascript, #scss, #html, #jQuery',
    href: ['https://sovidi.github.io/everland/'],
    githref: 'https://github.com/Sovidi/everland',
  },
  {
    id: 4,
    expired: false,
    name: 'Scary House',
    desc: '귀신의 집, 공포 추리 미니 게임',
    src: './assets/scaryhouse.png',
    skills: '#react, #scss, #html, #Express',
    href: ['https://sovidi.github.io/scary/'],
    githref: 'https://github.com/Sovidi/scary',
  },
  {
    id: 5,
    expired: false,
    name: 'Movie Finder',
    desc: 'MovieDB API를 활용한 무비 파인더',
    src: './assets/moviefinder.gif',
    skills: '#react, #scss, #html',
    href: ['https://sovidi.github.io/movies/'],
    githref: 'https://github.com/Sovidi/movies',
  },
  {
    id: 6,
    expired: false,
    name: 'BookFinder',
    desc: 'NaverBook RestAPI를 활용한 간단한 검색기',
    src: './assets/bookfinder.gif',
    skills: '#react, #scss, #html',
    href: ['https://book-finder-fawn-kappa.vercel.app/'],
    githref: 'https://github.com/Sovidi/BookFinder',
  },
  // {
  //   id: 7,
  //   expired: true,
  //   name: 'toGrocery (MySQL) *서버폐쇄',
  //   desc: '시장 농산물 물가현황 간편확인 및 위치기반 매칭 웹앱',
  //   src: './assets/togrocery.png',
  //   skills: '#next.js, #scss, #html, #MySQL',
  //   href: ['https://togrocery.vercel.app/'],
  //   githref: 'https://github.com/Sovidi/togrocery',
  // },
  {
    id: 8,
    expired: false,
    name: 'toGrocery (MongoDB)',
    desc: '시장 농산물 물가현황 간편확인 및 위치기반 매칭 웹앱, 서버코드를 MongoDB(NoSQL)로 바꾼 버전입니다.',
    src: './assets/togrocery.png',
    skills: '#next.js, #scss, #html, #MongoDB',
    href: ['https://to-grocery2.vercel.app/'],
    githref: 'https://github.com/Sovidi/toGrocery2',
  },
  {
    id: 9,
    expired: false,
    name: 'petSalon',
    desc: '미용사 찾기 위치기반 서비스 웹앱',
    src: './assets/petsalon.png',
    skills: '#react, #css, #html',
    href: ['https://pet-salon.vercel.app/'],
    githref: 'https://github.com/Sovidi/petSalon',
  },
  {
    id: 10,
    expired: false,
    name: '웅진 개정수학 e-book 컨텐츠',
    desc: '웅진과 계약된 개정수학의 2차 개정 컨텐츠 개발 산출물입니다. 2단원 개발에 합류하여 컨텐츠 2개 차시를 개발하였습니다. 컨텐츠 개발작업이 주류이며 게임, 개념익히기, 확인문제 3스텝으로 구분되어 있습니다. 과정중 학습문제 테마를 주로 개발하였습니다. 미니게임중 선잇기 개발 맡아 Canvas 활용하여 화면좌표와 뒤에있는 클릭점 좌표를 동기화 하여 선잇기 게임 개발하였습니다. 당시에 코드 포맷터나 Tailwind CSS 등이 적용되지 않아 공통부 코드 관리가 매우 어려웠으며, 차후 컨텐츠 개발에선 이를 개선하게 되는 계기가 된 프로젝트입니다.',
    src: './assets/wj_math.png',
    skills: '#javascript, #css, #html, #jquery',
    href: ['https://wj-revision-math-exported.vercel.app/%EC%96%91%EC%82%B02/2/2-2-3/INDEX3.HTML', 'https://wj-revision-math-exported.vercel.app/%EC%96%91%EC%82%B02/2/2-2-11/INDEX2.HTML', 'https://wj-revision-math-exported.vercel.app/%EC%96%91%EC%82%B02/2/2-2-4/INDEX1.HTML'],
    githref: 'https://github.com/Dalguiee/wj_revision_math_exported',
  },
  {
    id: 11,
    expired: false,
    name: '2024 TVing Festa 이벤트 페이지',
    desc: '2024년 하반기 TVing 이벤트 페이지 프로젝트입니다. 백그라운드는 긴 이미지를 통으로 활용하였고 내부 UI를 좌표 고정시켜 따로 작업하였습니다. 프로젝트 특성이 하루정도의 기간을 놓고 짧은시간 안에 이벤트페이지 산출하는게 목표인 프로젝트입니다. ios측 폰트 이슈로 중간 타이머의 경우 0부터 9까지 숫자가 길게 적힌 이미지의 좌표를 전환하며 글자를 출력시켰던 작업이 가장 인상깊습니다.',
    src: './assets/tving.png',
    skills: '#javascript, #css, #html, #jquery',
    href: ['https://dalguiee.github.io/tving_festa2024_exported/'],
    githref: 'https://github.com/Dalguiee/tving_festa2024_exported',
  },
  {
    id: 12,
    expired: false,
    name: '웅진 스마트올 중학',
    desc: '2024년 8월부터 웅진 스마트올중학 웹사이트 운영, 관리중에 있습니다. 프론트단은 JSP로 개발되어 있고 기존 코드가 전혀 정리되지 않고 여러 개발자의 손을 거친 상태였습니다. 제가 합류하여 추가수정 및 신규 페이지들은 기존 CSS 시스템을 사용하지 않고 Tailwind CSS로 변환하며 작업하였고 Node.js 모듈 통하여 Prettier 포맷터 추가하여 정리되지 않은 코드 정리 및 유지보수 난이도록 좁히도록 개선하였습니다.',
    src: './assets/smart_all_middle.png',
    skills: '#javascript, #css, #html, #jquery, #tailwind css',
    href: ['https://smartallmid.wjthinkbig.com/'],
  },
  {
    id: 13,
    expired: false,
    name: '프리스비',
    desc: '2024년 8월부터 애플 서드파티 브랜드인 프리스비의 프론트 운영, 관리중에 있습니다. 서버시스템은 Java 이며 프론트단도 JSP로 제작되어 있습니다. 처음 위임받은 후 했던 작업은, 버거메뉴 내부 프리스비 카테고리를 본래 터치시 해당 사이트로 bind만 하던 방식에서, 백엔드로부터 카테고리 데이터를 전달받아 하단 버거형식으로 세부항목들 나타나도록 교체하는 작업 맡았습니다. 이후 운영관리중에 있으며 2026년도부터 애플로부터 전달받은 스크립트가 JSP환경에서 작동되지 않는 이슈가 있어 몇몇 서브페이지에선 내부컨텐츠를 iframe 으로 감쌓아 불러오는 방식으로 수정하였습니다.',
    src: './assets/frisbee.png',
    skills: '#javascript, #css, #html, #jquery',
    href: ['https://www.frisbeekorea.com/shop/main/main.do'],
  },
  // { id: 14, name: "웅진 개정수학(선긋기 게임 컨텐츠)", desc: "게임 시스템 핵심코드 리펙토링 담당하였습니다.", src: "./assets/petsalon.png", skills: "#javascript, #css, #html, #jquery", href: "https://sovidi.github.io/exported_wj_revision_math/%EC%96%91%EC%82%B02/1/2-1-4/INDEX1.HTML", githref: "https://github.com/Sovidi/exported_wj_revision_math" },
  {
    id: 15,
    expired: false,
    name: '미래엔 고등 중국어 전자교과서 e-book 컨텐츠',
    desc: '2024년 후반부 미래엔과 계약한 e-book 개발 컨텐츠중 고등 중국어 컨텐츠 개발을 맡았습니다. 컨텐츠중 선긋기 게임 모듈 스크립트, 롤플레잉중 텍스트 하이라이트, 특수문자 자동 교환 등의 핵심스크립트 개발하였습니다. 일전 개발콘텐츠의 CSS 관리에 난항이 있어 플랫폼에 사용하고있는 Tailwind CSS를 적용하여 개발하였습니다.',
    src: './assets/miraen_high_china_title.png',
    skills: '#javascript, #css, #html, #jquery',
    href: [`https://www.onflou.com/@pj/miraen_contents_list/high_china/index.html`, 'https://miraen-contents-exported.vercel.app/high/china/contents/lesson02/ops/2/2_01_04.html', 'https://miraen-contents-exported.vercel.app/high/china/contents/lesson06/ops/6/6_01_08.html', 'https://miraen-contents-exported.vercel.app/high/china/contents/lesson07/ops/7/7_01_18.html'],
    githref: 'https://github.com/Dalguiee/miraen_contents_exported',
  },
  {
    id: 16,
    expired: false,
    name: 'CGN 통합페이지',
    desc: '온누리교회와의 계약으로 CGN 통합페이지 리뉴얼 작업하였고 현재 운영관리중에 있습니다. React.js + Vite 로 제작되었으며<br />클라이언트단은 애니메이션을 위한 framer-motion, Swiper.js, 상태관리를 위한 Zustand 라이브러리 등이 사용되었습니다.<br />각종 기능 및 버튼부는 모두 컴포넌트 모듈화로 공통적으로 사용할 수 있도록 디렉토리 및 구조 신경쓰며 제작하였습니다. 협업사의 요청으로 컴포넌트이 파일명은 대문자 시작하지 않으며 컴포넌트의 함수명 및 선언부에서만 대문자 유지하도록 설계되었습니다. 백엔드는 협업사와 진행하였습니다.',
    src: './assets/cgn_intergration.png',
    skills: '#react.js, #tailwind, #vite, #zustand',
    href: ['https://cgn-intergration-exported.vercel.app/'],
    githref: 'https://github.com/Dalguiee/cgn_intergration_exported',
  },
  {
    id: 17,
    expired: false,
    name: '웅진 서술형 과학 컨텐츠개발',
    desc: '웅진북클럽 플랫폼 과목중 초등과학 컨텐츠 서술형과학의 문항 개발 맡았습니다. 개별 html파일 개발형식이며 모듈형으로 제작되어 문항정보는 공통부 json 데이터로 저장하고 문항 갯수별로 html 산출하도록 구축하였습니다. 웅진측 브릿지 연결 통하여 String 저장할 수 있어 정답내용을 String 으로 파싱하여 웅진측 서버에 저장하고 불러오는 방식으로 정답저장 기능 구현되어 있습니다.',
    src: ['./assets/wj_sc_desc/screenshot_1.png', './assets/wj_sc_desc/screenshot_2.png', './assets/wj_sc_desc/screenshot_3.png', './assets/wj_sc_desc/screenshot_4.png', './assets/wj_sc_desc/screenshot_5.png'],
    skills: '#javascript, #tailwind, #jquery',
    href: ['https://wj-description-exported.vercel.app/2-WV/3-1-4/3-1-4-2/INDEX.HTML', `https://wj-description-exported.vercel.app/1-SV/3-2-2/3-2-2-1/INDEX.HTML`, `https://wj-description-exported.vercel.app/2-WV/3-1-1/3-1-1-3/INDEX.HTML`],
    githref: 'https://github.com/Dalguiee/wj_description_exported',
  },
  {
    id: 18,
    expired: false,
    name: '미래엔 SmartPPT 컨텐츠 다운로드형 및 S3형태변환 개발',
    desc: '미래엔과 계약된 SmartPPT 교육 컨텐츠의 경우 미래엔 SmartPPT 웹사이트의 서비스를 통한 제공되고 있으나, 오프라인환경 대응 요청을 받아 협력사와 함께 .exe 파일로 제작된 뷰어와 제공하게 되었습니다. 토브소프트사 로부터 exe뷰어를 제공받았으며 개발된 웹 소스를 해당 뷰어와 브릿지하는 작업 맡았습니다. 해당 뷰어는 교과서 pdf파일과 개발된 컨텐츠가 동기화되어 작동하는 구조로 되어있으며 교육자료 멀티미디어 파일 다운로드를 위한 자료실구현, 기존 업데이트기능의 이슈 해결, pdf 교과서 버튼기능을 위한 스크립트 등을 맡았습니다. 추가로 해당 뷰어의 UI를 그대로 다시 웹형태로도 구현하길 원하는 고객사 요청에 따라 내부 소스 추출 통하여 뷰어 내부에서 작동하던 navigation 을 웹 url 이동형태로 수정한 S3스타일 변환작업 맡아 진행하였습니다.',
    src: ['./assets/smartppt_download/screenshot_1.png', './assets/smartppt_download/screenshot_2.png', './assets/smartppt_download/screenshot_3.png', './assets/smartppt_download/screenshot_4.png', './assets/smartppt_download/screenshot_5.png', './assets/smartppt_download/screenshot_6.png', './assets/smartppt_download/screenshot_7.png'],
    skills: '#javascript, #tailwind, #jquery',
    href: ['https://download.m-teacher.co.kr/high/chi/core/resource/include/main/index.html', `https://download.m-teacher.co.kr/high/jpn/culture/resource/include/main/index.html`, `https://download.m-teacher.co.kr/high/phy/culture/resource/include/main/index.html`],
    // githref: 'https://github.com/Dalguiee/cgn_intergration_exported',
  },
  {
    id: 19,
    expired: false,
    name: '미래엔 초코 달달영어',
    desc: '미래엔 초코 과목플랫폼중 영어과목 개발 진행중인 프로젝트에 투입되어 진행하였습니다. 플랫폼 전체의 패드화면 대응을 필요로 하여 작업하였고 안드로이드와 ios 간의 분기개발을 하였습니다. 서브페이지로는 튜토리얼 및 과목시작 인트로 페이지, 달영노트 및 영단어사전 개발 및 api로부터 받은 데이터 리스팅 하는 작업 맡았습니다. 영단어사전 또한 미래엔에서 제공한 영어사전 api로부터 전달받은 데이터 리스팅 작업 및 화면 퍼블리싱 작업 하였습니다. 기존 프로젝트 선임자에 의해 많은 컴포넌트가 작성된 상태였으므로 구조를 파악하는데 주의를 기울였으며 기존구조를 깨트리지 않는데 집중하였습니다.',
    src: ['./assets/daldaleng/screenshot_1.png', './assets/daldaleng/screenshot_2.png', './assets/daldaleng/screenshot_3.png'],
    skills: '#react.js, #tailwind, #vite, #zustand, #axios, #react-query',
    href: ['https://stg.miraenchoco.com/gate'],
    // githref: 'https://github.com/Dalguiee/cgn_intergration_exported',
  },
  {
    id: 20,
    expired: false,
    name: '서강대학교 SLP Edu Platform',
    desc: '서강대학교 SLP 통합페이지와 교육플랫폼인 Edu SLP 관련하여 오래된 프로젝트를 리뉴얼한 프로젝트입니다. 본래 JSP로 구성된 클라이언트단은 React.js + Vite로 리뉴얼 하였으며, 백엔드 시스템도 PHP로 작성된 서버코드를 백엔드 팀에서 Java로 리워크하였습니다. 클라이언트 서브페이지중 포트폴리오 맡아 교육 리스팅, 작성페이지 퍼블리싱 및 연결, api 연결 대비하여 컴포넌트로 구축 작업 하였습니다.',
    src: ['./assets/edu_slp/screenshot_1.png', './assets/edu_slp/screenshot_2.png', './assets/edu_slp/screenshot_3.png', './assets/edu_slp/screenshot_4.png', './assets/edu_slp/screenshot_5.png', './assets/edu_slp/screenshot_6.png'],
    skills: '#react.js, #tailwind, #vite, #zustand, #axios, #react-query',
    href: ['https://beta.eduslp.ac.kr/'],
    // githref: 'https://github.com/Dalguiee/cgn_intergration_exported',
  },
  {
    id: 21,
    expired: false,
    name: '서강대학교 SLP Edu Platform Application',
    desc: '리뉴얼한 SLP Edu 웹페이지를 React-Native의 WebView 기능 사용하여 어플리케이션으로 제공하고자 하여 프로젝트 맡게 되었습니다. 소스가 웹이다 보니 Capacitor로도 구현될 가능성 있었으나 온라인서비스 특성상 오프라인 기능 불필요하여 Expo를 통하여 WebView 앱으로 결정되었습니다. WebView의 Script Injection 기능 통하여 페이지별로 구분시켜 네이티브 기능 구현할 수 있었고, 본래 리액트로 구축되어 웹앱으로써 앱으로 패키징하는데 큰 하자 없었습니다. 외부페이지로 이동할 경우에만 어플리케이션 외부로 연결되도록 분기처리 되어있습니다. 페이지별 분기로 구현된 기능중엔, 교육 팝업 페이지의 경우 본래 Blank로 처리되어 있으나 url을 이동하도록 Monkey Patch 구현하였습니다. 또한 교육컨텐츠중 마이크접근 및 녹음기능 필요하여 Native 권한으로 접근시켰으며 카메라 및 알림권한 위한 접근컴포넌트 및 설정화면 위한 Stack 별도처리 등 작업하였습니다.',
    src: ['./assets/edu_slp_app/screenshot_2.png', './assets/edu_slp_app/screenshot_3.png', './assets/edu_slp_app/screenshot_4.png', './assets/edu_slp_app/screenshot_5.png', './assets/edu_slp_app/screenshot_6.png', './assets/edu_slp_app/screenshot_7.png', './assets/edu_slp_app/screenshot_8.png'],
    skills: '#Expo, #tailwind, #zustand, #reanimated, #moti',
    // href: ['https://cgn-intergration-exported.vercel.app/'],
    // githref: 'https://github.com/Dalguiee/cgn_intergration_exported',
  },
];
